source "https://supermarket.chef.io"

cookbook 'apt', '~> 2.7.0'
cookbook 'java', '~> 1.31.0'
#cookbook 'ark', git: 'https://github.com/opscode-cookbooks/ark.git', tag: 'v0.9.0'
#cookbook 'bluepill', '>= 2.3.1', git: 'https://github.com/opscode-cookbooks/bluepill.git', tag: 'v2.3.1'
#cookbook 'build-essential', '>= 1.4.2', git: 'https://github.com/opscode-cookbooks/build-essential.git', tag: 'v2.1.2'
#cookbook 'monit', '>= 0.6', git: 'https://github.com/apsoto/monit.git'
#cookbook 'ohai', '>= 1.1.12', git: 'https://github.com/opscode-cookbooks/ohai.git', tag: 'v2.0.1'
#cookbook 'python', '>= 1.4.6', git: 'https://github.com/poise/python.git', tag: 'v1.4.6'
#cookbook 'rsyslog', '>= 1.11.0', git: 'https://github.com/opscode-cookbooks/rsyslog.git', tag: 'v1.11.0'
#cookbook 'windows', '>= 1.30.0', git: 'https://github.com/opscode-cookbooks/windows.git', tag: 'v1.30.2'
#cookbook 'yum', git: 'https://github.com/opscode-cookbooks/yum.git', tag: 'v3.4.0'
#cookbook 'yum-epel', '>= 0.3.4', git: 'https://github.com/opscode-cookbooks/yum-epel.git', tag: 'v0.5.1'
#cookbook 'elasticsearch', git: 'https://github.com/elasticsearch/cookbook-elasticsearch.git', tag: '0.3.11'
cookbook 'elasticsearch', '= 0.3.14'
#cookbook 'mongodb', git: 'https://github.com/edelight/chef-mongodb.git'
#cookbook 'papertrail', git: 'https://github.com/librato/papertrail-cookbook.git', tag: '0.0.7'
cookbook 'docker', git: 'https://github.com/intinig/opsworks-docker.git'
